const REQUEST = {
    UPDATE_THEME: 'UPDATE_THEME',
    REQUESTED_DATA: 'REQUESTED_DATA',
    REQUEST_FINISHED: 'REQUEST_FINISHED',
    ADD_ERROR_MESSAGE: 'ADD_ERROR_MESSAGE',
    CLEAR_ERROR_MESSAGE: 'CLEAR_ERROR_MESSAGE',
    ADD_NEW_POST: 'ADD_NEW_POST',
    REMOVE_POST: 'REMOVE_POST',
    CHANGE_POST_STATUS: 'CHANGE_POST_STATUS'
};

const CONST = {
    SERVER_HOST: 'https://www.reddit.com/r',
    API_KEY: 'ac45bb49a0mshca48265691cce65p125ba2jsn25a988169c83'
};
  
export { REQUEST, CONST };