const REQUEST = {
    UPDATE_THEME: 'UPDATE_THEME',
    REQUESTED_DATA: 'REQUESTED_DATA',
    REQUEST_DATA_SUCCEEDED: 'REQUEST_DATA_SUCCEEDED',
    REQUEST_DATA_FAILED: 'REQUEST_DATA_FAILED',
    ADD_ERROR_MESSAGE: 'ADD_ERROR_MESSAGE',
    CLEAR_ERROR_MESSAGE: 'CLEAR_ERROR_MESSAGE'
};

const CONST = {
    SERVER_HOST: 'https://www.reddit.com/r',
    API_KEY: 'ac45bb49a0mshca48265691cce65p125ba2jsn25a988169c83'
};
  
export { REQUEST, CONST };